### ISSUE TITLE
If you install Tabs-extension, the Postprocessing Upscale UI will disappear.

### ISSUE THREAD

**Issue by DDaDaDak** [Haoming02/sd-webui-tabs-extension#11]
If you install Tabs-extension with Postprocessing Upscale menu UI enabled in WebUI settings, the Upscale menu UI will disappear.

I use the Postprocessing Upscale feature in WebUI in addition to Hires Fix.
Can you improve this part?

![2024-04-04 152858](https://github.com/Haoming02/sd-webui-tabs-extension/assets/130622793/42f54b27-8a83-46e1-b676-8b7f32f8186c)

![2024-04-04 152739](https://github.com/Haoming02/sd-webui-tabs-extension/assets/130622793/fb667139-3896-4415-ae4f-355c4a027946)

**Comment by Haoming02** [comment]
oof, ~~yet another feature that I don't use~~ 

I'll look into it

**Comment by DDaDaDak** [comment]
A1111 There were changes to the UI I mentioned in version 1.9.0-RC that made it compatible with your extension.
So I guess you can close this issue.
