### ISSUE TITLE
Style is invalid on webui1.10

### ISSUE THREAD

**Issue by tangcan1600** [Haoming02/sd-webui-tabs-extension#15]

**Comment by Haoming02** [comment]
Uhh...

wdym?

**Comment by tangcan1600** [comment]
After updating the latest version of the web UI, the button style of tabs_extension cannot be displayed correctly. Later, I discovered that this was caused by other reasons rather than the plugin itself. Now it can be displayed normally, but it is causing the extended page to still be in the loading process, and the SD webui cannot release memory correctly after generating the image, resulting in memory being full.



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 29, 2024 11:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Haoming02/sd-webui-tabs-extension] Style is invalid on webui1.10(Issue #15)




 
Uhh...
 
wdym?

**Comment by Haoming02** [comment]
That still sounds like issue from other Extensions?

Cause this one has nothing to do with generation and memory
