### ISSUE TITLE
[Feature Request] Option to exclude extensions/place above or below Tabs

### ISSUE THREAD

**Issue by StylusEcho** [Haoming02/sd-webui-tabs-extension#16]
Perhaps in addition to the left and right options in tabs_config.csv, there should also be a "none" option to exclude specific items so that they display as normal.

I don't know if it's possible but would could be even better is "above" and "below" options, for instance I could have the extension "Aspect Ratio and Resolution buttons" always above the Tabs, and Scripts always below.

**Comment by Haoming02** [comment]
You can now set the **Aspect Ratio and Resolution Buttons** extension to `above` in the config~
