### ISSUE TITLE
Issue with Openpose Editor send to text2img and img2img buttons with sd-webui-tabs-extension installed.

### ISSUE THREAD

**Issue by Sicnics** [Haoming02/sd-webui-tabs-extension#18]
Openpose editor send to text2img and img2img buttons do not work with this addon installed.
When these buttons are pressed the loaded pose does not appear in the controlnet section.

If i disable the sd-webui-tabs-extension addon this function works fine.

**Comment by Haoming02** [comment]
If you meant this [repo](https://github.com/fkunn1326/openpose-editor), whose last update was ~10 months ago, I probably won't support it.

From briefly looking through the code, it uses some really convoluted way to find the ControlNet input. So if I were to support it, I have to recreate the entire structure that it expects one by one...

And yes, I did try other Extension with "Send to Controlnet" feature and they worked fine.

**Comment by Haoming02** [comment]
Wrote a fork that works with this:

https://github.com/Haoming02/sd-webui-openpose-editor

**Comment by Sicnics** [comment]
Hey Haoming02

This version of openpose editorworks perfect with the tab addon!!! 
Thank you so so much for that. 
I really like that tabs addon. Makes the whole interface less cluttered. 

I did notice 1 issue  when installing it from the "install from url" option in the webui.
Its wanting to download to the wrong addon folder 
It downloads to "sd-webui-openpose-editor" folder which is another already existing addon. (https://github.com/huchenlei/sd-webui-openpose-editor)
It should be downloading to "openpose-editor" folder
Its such a minor thing and i got it working fine but i just thought id let you know for other people to use.

Thanks again Haoming02

**Comment by Haoming02** [comment]
> "sd-webui-openpose-editor" folder which is another already existing addon

Oh lol, name collision...

Welp, just use `Local directory name` if someone wants to install both I guess

I want to keep my extension naming consistent :P
