### ISSUE TITLE
The extension blocks Dynamic Thresholding from toggle

### ISSUE THREAD

**Issue by enternalsaga** [Haoming02/sd-webui-tabs-extension#2]
![image](https://github.com/Haoming02/sd-webui-tabs-extension/assets/31148570/b72e10b4-95b6-472e-ac6f-86d9bf4d5221)
somehow after batch updating all extensions I could not enable or disable this button, whenever I hover my cursor to the checkbox It turns to block symbol??? Any help?
Thank you.

**Comment by Haoming02** [comment]
The `checkbox` should be clickable now!

*(Though right now it throws a null referene error since the `Accordion` thingy is removed. Currently thinking of a good way to work around this...)* (Doesn't affect user functionality)

**Comment by Haoming02** [comment]
> throws a null referene error

Solved in the latest commit~

**Comment by enternalsaga** [comment]
works great! thanks.
