### ISSUE TITLE
New bugs introduced in latest commit

### ISSUE THREAD

**Issue by StylusEcho** [Haoming02/sd-webui-tabs-extension#20]
First of all thank you very much for implementing #16, from initial testing it seems to work exactly how I imagined.

However it seems like a couple of of bugs have been introduced.

1. Under certain conditions, the textbox for tab_configs.csv doesn't seem to go away on Microsoft Edge, meanwhile on Firefox it disappears about the same time that Extra Networks are fully loaded.
In these instances, clicking Save does not save any changes to the file either. There appears to be some correlation with the number of extensions installed, or it could be caused by a specific extension, still investigating.
2. With Lobe Theme installed, above Tabs Extension these empty blocks appear:
![image](https://github.com/user-attachments/assets/4908aef3-a6ef-4613-a185-e31b746eeee7)

**Comment by Haoming02** [comment]
The empty blocks mentioned in `2.` is fixed~

As for the textbox mentioned in `1.`, increasing the `Delay` in Settings *(so that it tries to save **after** Lobe theme does its thing)* seems to work for me.

**Comment by LindezaBlue** [comment]
For me it messes with my defaults from being enabled to disabled. On top of that I get that setting box as well. Really annoying.
![image](https://github.com/user-attachments/assets/9fb30bc9-f13c-4663-9515-70a66dcd8057)

**Comment by LindezaBlue** [comment]
> The empty blocks mentioned in `2.` is fixed~
> 
> As for the textbox mentioned in `1.`, increasing the `Delay` in Settings _(so that it tries to save **after** Lobe theme does its thing)_ seems to work for me.

Where are these "settings" you speak of? I am not seeing anything in A1111 that allows the editing of the "Delay."

**Comment by Haoming02** [comment]
> Where are these "settings" you speak of?

<p align="center"><img src="https://github.com/user-attachments/assets/c05b4f54-8dd1-4bc4-81c9-c1f9fc58faf5"></p>

**Comment by vis223** [comment]
![image](https://github.com/user-attachments/assets/0b407ee3-45ff-401e-a113-b3fa55d6721b)

This appears on loading. Hitting 'save' has no effect apart from it all disappearing. Works fine in img2img. I pushed the delay to the highest setting but with no effect.

I'd want to investigate the differences between t2i and i2i. Can't help feeling there may just be one or two parameters difference that's throwing it out. 
Sadly, I don't code but thought I'd mention it in case it's a thing.

Thanks for the great extension. Having things break like this makes me appreciate how indispensable this is.  It's very frustrating and I hope there's a simple fix soon.

**Comment by Haoming02** [comment]
@vis223 Which UI are you using? And can you give me the list of all your Extensions?

**Comment by vis223** [comment]
version: v1.10.0-RC-60-g8b3d98c5

SDXL Styles,  ADetailer,Dynamic Prompts,Dynamic Thresholding (CFG Scale Fix), Diffusion CG, Memory Release, FABRIC, A Person Mask Generator, ControlNet, NegPiP, Attention 
Heatmap, 
Regional Prompter, CADS, Fooocus Expansion, Aspect Ratio and Resolution, Scramble Prompts [M9], Tweak Weights [M9], Detail Daemon, Refiner, Multi-Prompt Manager,

Does that give you the info you need?

**Comment by Haoming02** [comment]
> ` v1.10.0-RC-60-g8b3d98c5`

Hmm, is that **reForge**?

**Comment by ride5k** [comment]
having same issue of persistent text block.  extension list cut and pasted from box:

,txt,img
tabs,left,right
default,left,right
GFPGAN,left,right
CodeFormer,left,right
ADetailer,left,right
Tiled Diffusion,left,right
DemoFusion,left,right
Tiled VAE,left,right
Face Editor,left,right
Aspect Ratio Helper,left,right
ControlNet,left,right
Cutoff,left,right
Kohya Hires.fix,left,right
LoRA Block Weight : Active,left,right
Dynamic Lora Weights,left,right
Scripts,left,right
A Person Mask Generator,left,right
Segment Anything,left,right
Upscale,left,right
CADS,left,right
Diffusion CG,left,right
ReSharpen,left,right
Detail Daemon,left,right

**Comment by Haoming02** [comment]
Welp... I just cross checked the two lists, and installed all the shared ones, as well as checking out some of those that I've never heard of before, but I still don't get any issue...

Please update to the latest version, and see what error logs do you get.

**Comment by Haoming02** [comment]
>  appears to be some correlation with the number of extensions installed

Probably not. Just tried with 25 Extensions that have accordion, and still no issues...

**Comment by vis223** [comment]
Everything is up to date. I'm not exactly sure which log files you'd need. 
Is that the A1111 log file? Do I need to turn on debug mode or something?

What doesn't make sense to me is why it all works as it should on the image to image page but not on the text to image page. Surely if it was a conflict with a plug in then it wouldn't work on either?

**Comment by LindezaBlue** [comment]
> > Where are these "settings" you speak of?
> 
> ![](https://private-user-images.githubusercontent.com/73768377/359696483-c05b4f54-8dd1-4bc4-81c9-c1f9fc58faf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzAzMjQsIm5iZiI6MTcyNDQzMDAyNCwicGF0aCI6Ii83Mzc2ODM3Ny8zNTk2OTY0ODMtYzA1YjRmNTQtOGRkMS00YmM0LTgxYzktYzFmOWZjNThmYWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE2MjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwOTNjYWVlM2Q3MWY3YmZkYjNlNmJlMTJjN2E3NmRhYTY3MTNhNjE3YjQ3ZjY4MGU5ZDVkMGMwNDBkYWNkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aud9PvG1DHL0aXs7TSCDgj5Twyk03V1GW4BztM6qCHE)

Thanks for sharing where it was, I couldn't find it anywhere. Was racking my brain for days trying to find it.

Anyways, is there anything you can do to have the extension respect A1111 user defaults? When the extension is disabled/removed defaults work as intended and revert to what I had set for my defaults. But when I load the extension, all defaults switch to being disabled.

![image](https://github.com/user-attachments/assets/1715c1df-42ca-4d04-b80a-de399019ae4b)

Adetailer, and TiledVAE usually are enabled as per my defaults, but with the extension messes with those defaults and disables them. I also can't set any new defaults with when the extension is installed. Not sure why this is the case, but defaults are only affected when I have the Tab Extension installed into A1111.
__________

**Updated to the latest commit as of 8/24/2024:**
![image](https://github.com/user-attachments/assets/24096882-4749-4341-805e-551803204e64)

adjusting the settings for the Delay has no effect. However it does seem to respect the UI Defaults now.. will continue to watch and see if it stays consistently respectful of the Defaults.

**Comment by vis223** [comment]
![image](https://github.com/user-attachments/assets/55a28d19-afbd-4f69-8fab-b02e11f5f99d)

Thanks a million, your last commit appears to have fixed the problem.
Well done. I hope that's it for fixed everyone else having issues too.
Your extension is totally essential and  A1111 was a complete mess without it.
All the best.

**Comment by StylusEcho** [comment]
Sorry, been away for a bit, but gave things a try with the latest commit.
It looks like all issues I mentioned were resolved, so thanks a lot. This small cosmetic issue remains:
![image](https://github.com/user-attachments/assets/a1df689e-e359-4475-b892-df32f9d8629a)
A blank space above. It is the first element inside the div "txt2img_script_container" and has the class "styler svelte-iyf88w".
If it's too trivial I'll just block the element with my adblocker, it's not a big deal, but I thought i'd point it out.

**Comment by Haoming02** [comment]
Added a new setting to hide the container~

**Comment by LindezaBlue** [comment]
seems to be fixed now, thank you!

**Comment by StylusEcho** [comment]
Everything is perfect now! Thanks a lot.
