### ISSUE TITLE
[TabsExtension] Configs issue

### ISSUE THREAD

**Issue by kuschanow** [Haoming02/sd-webui-tabs-extension#22]
After updating the extension I get this window. The new extensions that I installed do not affect this. There are no errors in the console.
![image](https://github.com/user-attachments/assets/825c62f9-6281-426b-88ea-be99abf1717e)

**Comment by kuschanow** [comment]
Very strange. I restarted the console several times, and it didn't go away, but on the fifth time, it went away 😅

**Comment by kuschanow** [comment]
Just in case, I will provide a list of extensions
![image](https://github.com/user-attachments/assets/c63115c5-14a1-4414-b30d-6b85fc18ab96)

**Comment by RomanKuschanow** [comment]
Now I noticed that this happens when I "Reload UI". But everything is OK when I completely restart them.

**Comment by kuschanow** [comment]
This keeps happening completely unpredictably.

**Comment by Haoming02** [comment]
May I know if the issue still persists?

As the same issue seems to have been fixed for others in `#20`

**Comment by kuschanow** [comment]
When I last checked the problem was still present in 80% of cases, disappearing is not clear after what actions

**Comment by Haoming02** [comment]
Were there any error popup on your browser?

**Comment by kuschanow** [comment]
No. Everything is clean in the console and browser

**Comment by Haoming02** [comment]
How the... T-T

**Comment by kuschanow** [comment]
Now I checked, installed the latest update and it still doesn’t work (although before installing the update when I just launched it, it removed this field)

**Comment by Haoming02** [comment]
When the textbox didn't disappear, did other Extensions get turned into tabs at least? Or are they also still in the dropdown thingy?

**Comment by kuschanow** [comment]
They turn into tabs and these tabs work properly
