### ISSUE TITLE
[TabsExtension] Configs - SDXL Styles

### ISSUE THREAD

**Issue by GeekDadKevin** [Haoming02/sd-webui-tabs-extension#24]
,txt,img
tabs,left,right
default,left,right
ControlNet,left,right
Scripts,left,right
Aspect Ratio and Resolution Buttons,left,right
ADetailer,left,right
SDXL Styles,left,right
Dynamic Prompts,left,right
AnimateDiff,left,right

SDXL Styles seems like it may be the issue but I cannot confirm that as clicking SDXL Styles and then on another tab solves the issue.

**Comment by Haoming02** [comment]
What issue? The Config Textbox not disappearing?

> clicking SDXL Styles and then on another tab solves the issue

What does this mean?

> but I cannot confirm that 

Simply disable the Extension and restart the Webui to see if your issue stops. Cause I just looked at the code and this particular Extension does nothing special, and shouldn't have caused any issues.

**Comment by Haoming02** [comment]
Yep, just tested it myself:

<p align="center"><img src="https://github.com/user-attachments/assets/fc2eb291-3dd6-4668-a83e-5cff7c3fbb89"></p>
