### ISSUE TITLE
Free controlnet image canvas from tab zone when in Full screen mode.

### ISSUE THREAD

**Issue by enternalsaga** [Haoming02/sd-webui-tabs-extension#3]
![image](https://github.com/Haoming02/sd-webui-tabs-extension/assets/31148570/d4846e35-87fe-45ac-9a0e-4716537fd346)
Hi again, any chance you can fix Controlnet canvas to be in full screen mode?
Thank you.

**Comment by Haoming02** [comment]
~~That's a lot of Extensions~~

How do I enter/trigger that mode?
