### ISSUE TITLE
[Platform Support] Add support for new sd-webui-forge

### ISSUE THREAD

**Issue by enternalsaga** [Haoming02/sd-webui-tabs-extension#4]
Hi, There's newly released a1111 based platform via https://github.com/lllyasviel/stable-diffusion-webui-forge made by LLLyasviel, can you think of a way to make this extension adapt to it? I want to migrate all my extensions to it and your extension is really important. The dev stated that building extension for forge would be much easier than the origin.
Thank you.

**Comment by Haoming02** [comment]
Aight, I'll probably do it next week _(on vaca rn)_

> building extension for forge would be much easier

That's referring to extensions that involve the Unet btw, not the UI ones
