### ISSUE TITLE
Tab positioning is broken on Firefox and Chrome, shows tabs vertically instead of horizontally

### ISSUE THREAD

**Issue by SunGod** [Haoming02/sd-webui-tabs-extension#5]
Unfortunately it looks like the tab positioning in both Firefox and Chrome is broken, as tabs are stacked vertically instead of ordered horizontally. (I am using LobeHub for the UI, well, because it's awesome and far superior to the default A1111 UI. Not sure if this has any impact on the issue.)

Additonally, editing the tab_configs.csv (or deleting it and restarting the UI so it creates a new default config file) to change left/right values doesn't seem to make any difference. I've tried changing txt and img settings to all left or all right, and it doesn't seem to matter. (It'd be helpful if the documentation explained what txt and img columns are used for and give examples of how changing them changes what appears in the UI).

How it looks:
![Screenshot 2024-02-29 110555](https://github.com/Haoming02/sd-webui-tabs-extension/assets/2029061/10b30f21-e8e0-4086-982c-924bb3bc2861)

In the settings (changing them doesn't make any difference): 
![Screenshot 2024-02-29 111226](https://github.com/Haoming02/sd-webui-tabs-extension/assets/2029061/41e17e9b-c6c6-4931-8bd8-f4627a446954)

I really love the idea of what this extension promises to offer, so hopefully there's either an easy fix either to the extension itself or the way I have my A1111/LobeHub configured.

**Comment by Haoming02** [comment]
Should both be fixed now

*(Glad that the **Lobe** theme is just a `CSS` issue...)*

**Comment by SunGod** [comment]
Thank you for the quick fix! Verify it looks much better and is now horizontally arranged in LobeHub/A1111 in Firefox.
