### ISSUE TITLE
REQUEST: Honour Gradio theme settings

### ISSUE THREAD

**Issue by tusharbhutt** [Haoming02/sd-webui-tabs-extension#6]
This is a pretty cool extension, but it's harsh on the eyes!  In my UI, it looks like this:

![image](https://github.com/Haoming02/sd-webui-tabs-extension/assets/26264462/ed820860-e61b-440f-b669-d0c7177d4c91)

It seems it's not getting the correct font colours and styles from the GRadio theme.

Cheers,

TB.

**Comment by Haoming02** [comment]
Couldn't find a good *variable* to set the text color to, so I made it into a customizable option instead.

**Comment by tusharbhutt** [comment]
Thanks, will check it out.
