### ISSUE TITLE
Anyway to reorder extension Tabs?

### ISSUE THREAD

**Issue by mocmocmoc** [Haoming02/sd-webui-tabs-extension#7]
Possible to display extensions in Tabs according to the order in tab_configs.csv?

**Comment by Haoming02** [comment]
Oh, good idea.
I'll try adding that tomorrow.

**Comment by mocmocmoc** [comment]
> Oh, good idea. I'll try adding that tomorrow.

Thank you!
Maybe also add the "t2i/i2i Options" to tabs? (This is in the Settings>User Interface>Settings in UI)

At the moment it's way below https://i.imgur.com/0AHWMcD.png

**Comment by Haoming02** [comment]
Ah, OK.
~~Never used that feature XD~~

**Comment by Haoming02** [comment]
Both should work now~

**Comment by mocmocmoc** [comment]
Both works perfectly! Thank you!
This is easily my fav UI extension.
