### ISSUE TITLE
After upgrading, does not work (forge)

### ISSUE THREAD

**Issue by cibernicola** [Haoming02/sd-webui-tabs-extension#9]
Today (16/03/2024) I updated the extension and it does not work. There is no error anywhere, but the extensions are displayed as if before. The configuration sections do appear. Any clues?

PS: The idea of this extension is one of the best in GUI I've seen.

**Comment by Haoming02** [comment]
Hmm. It's working on my Forge installation.
Please open the console on your **browser**, see if there is any error.
It might another case of incompatible Extension.

**Comment by cibernicola** [comment]
Got it:

Problem with 
```
\sd-webui-tabs-extension\scripts\tabs_config.py line 16, in load_data
` UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 208: invalid start byte`
```
Due, I'm almost sure, by the extension name "μ Detection Detailer" with I can see in csv like "� Detection Detailer,left,right". 

Changing line 15 in tabs_config.py
`with open(CONFIG_FILE, "r", encoding="utf-8",) as csv_file:`
with
` with open(CONFIG_FILE, "r", encoding="utf-8", **errors='ignore'**) as csv_file:`

Its working now :)

**Comment by Haoming02** [comment]
Hmm, interesting
Good to know
